apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlops-work
spec:
  capacity:
    storage: 20Gi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /Users/shpileva/Desktop/big_data/mlops_project_lab8/storage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-work
  namespace: mlops
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ""
  volumeName: mlops-work
  resources:
    requests:
      storage: 20Gi
